/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.parcial.vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author paisa
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    //TODO: poner algo en el placeholder jeje

    /**
     * Permitir el acceso al label para así colocar un nuevo tip distinto
     * cada vez que se abra la aplicación
     * @return el label de los tips 
     */
    public JLabel getlTips(){
        return lTips;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lTextoExtra = new javax.swing.JLabel();
        lLogo = new javax.swing.JLabel();
        lTips = new javax.swing.JLabel();
        lGif = new javax.swing.JLabel();

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitulo.setBackground(new java.awt.Color(102, 255, 102));
        lTitulo.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(2, 68, 129));
        lTitulo.setText("Fauna Freaks");
        bg.add(lTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, -1, -1));

        lTextoExtra.setBackground(new java.awt.Color(2, 160, 225));
        lTextoExtra.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lTextoExtra.setForeground(new java.awt.Color(0, 159, 224));
        lTextoExtra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTextoExtra.setText("<html><center>Administra y consulta tus mascotas exóticas<br>de manera rápida y organizada.</center></html>");
        bg.add(lTextoExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 323, -1));

        lLogo.setBackground(new java.awt.Color(102, 102, 0));
        lLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adobe Express - file.png"))); // NOI18N
        lLogo.setText("jLabel3");
        bg.add(lLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 180, 180));

        lTips.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        bg.add(lTips, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 370, 220));

        lGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/placeholder.gif"))); // NOI18N
        lGif.setText("jLabel3");
        lGif.setMaximumSize(new java.awt.Dimension(450, 249));
        lGif.setMinimumSize(new java.awt.Dimension(450, 249));
        lGif.setPreferredSize(new java.awt.Dimension(450, 249));
        bg.add(lGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 350, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel lGif;
    private javax.swing.JLabel lLogo;
    private javax.swing.JLabel lTextoExtra;
    private javax.swing.JLabel lTips;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
