/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.parcial.vista;

import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author paisa
 */
public class PanelAdicionar extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdicionar
     */
    public PanelAdicionar() {
        initComponents();
    }

    public JTextField getCajaApodo() {
        return cajaApodo;
    }

    public JTextField getCajaEspecie() {
        return cajaEspecie;
    }

    public JTextField getCajaFamilia() {
        return cajaFamilia;
    }

    public JTextField getCajaGenero() {
        return cajaGenero;
    }

    public JTextField getCajaNombre() {
        return cajaNombre;
    }

    public JComboBox getComboClasificacion() {
        return comboClasificacion;
    }

    public JComboBox getComboAlimentacion() {
        return comboAlimentacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        panelInterno = new javax.swing.JPanel();
        lNombre = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        lApodo = new javax.swing.JLabel();
        cajaApodo = new javax.swing.JTextField();
        lClasificacion = new javax.swing.JLabel();
        comboClasificacion = new javax.swing.JComboBox<>();
        lTextoExtra = new javax.swing.JLabel();
        lFamilia = new javax.swing.JLabel();
        cajaFamilia = new javax.swing.JTextField();
        lGenero = new javax.swing.JLabel();
        cajaGenero = new javax.swing.JTextField();
        lEspecie = new javax.swing.JLabel();
        cajaEspecie = new javax.swing.JTextField();
        lAlimentacion = new javax.swing.JLabel();
        comboAlimentacion = new javax.swing.JComboBox<>();
        botonAdicionar = new javax.swing.JButton();

        lTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(2, 68, 129));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Adicionar");

        lNombre.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lNombre.setText("Nombre Común:");

        lApodo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lApodo.setText("Apodo:");

        lClasificacion.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lClasificacion.setText("Clasificación:");

        lTextoExtra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lTextoExtra.setForeground(new java.awt.Color(0, 159, 224));
        lTextoExtra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTextoExtra.setText("Nuevo Animal");

        lFamilia.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lFamilia.setText("Familia:");

        lGenero.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lGenero.setText("Género:");

        lEspecie.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lEspecie.setText("Especie:");

        lAlimentacion.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lAlimentacion.setText("Alimentación:");

        botonAdicionar.setBackground(new java.awt.Color(2, 68, 129));
        botonAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        botonAdicionar.setText("Adicionar");
        botonAdicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 159, 224), null, null));

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lTextoExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInternoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(lApodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lClasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lAlimentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cajaApodo)
                                .addComponent(cajaNombre)
                                .addComponent(comboClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cajaFamilia)
                                .addComponent(cajaGenero)
                                .addComponent(cajaEspecie)
                                .addComponent(comboAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lTextoExtra)
                .addGap(18, 18, 18)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lApodo)
                    .addComponent(cajaApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lClasificacion)
                    .addComponent(comboClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFamilia)
                    .addComponent(cajaFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGenero)
                    .addComponent(cajaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEspecie)
                    .addComponent(cajaEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAlimentacion)
                    .addComponent(comboAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(botonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(panelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lTitulo)
                .addGap(18, 18, 18)
                .addComponent(panelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton botonAdicionar;
    private javax.swing.JTextField cajaApodo;
    private javax.swing.JTextField cajaEspecie;
    private javax.swing.JTextField cajaFamilia;
    private javax.swing.JTextField cajaGenero;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JComboBox<String> comboAlimentacion;
    private javax.swing.JComboBox<String> comboClasificacion;
    private javax.swing.JLabel lAlimentacion;
    private javax.swing.JLabel lApodo;
    private javax.swing.JLabel lClasificacion;
    private javax.swing.JLabel lEspecie;
    private javax.swing.JLabel lFamilia;
    private javax.swing.JLabel lGenero;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTextoExtra;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel panelInterno;
    // End of variables declaration//GEN-END:variables
}
