package udistrital.avanzada.parcial.vista;

import udistrital.avanzada.parcial.control.ControlInterfaz;

import net.miginfocom.swing.MigLayout;


/**
 * Clase VentanaPrincipal es la ventana principal del proyecto
 *
 * @author Paula Martínez
 * @version 1.0
 * @since 2025-10-09
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControlInterfaz cInterfaz;
    
    private MigLayout layout;
    private Menu menu;
    private Header header;
    private MainForm main;
    
    public VentanaPrincipal(ControlInterfaz cInterfaz) {
        initComponents();
        init();
    }

    private void init(){
        layout = new MigLayout("fill", "0[]0[100%,fill]0", "0[fill,top]0");
        bg.setLayout(layout);
        menu = new Menu();
        header = new Header();
        main = new MainForm();
        bg.add(menu,"w 230!, spany 2");
        bg.add(header, "h 50!, wrap");
        bg.add(main, "w 100%, h 100%");
        this.setLocationRelativeTo(null);
    }
    /**
     * Permite acceder al panel de menú desde otras clases.
     * @return el panel de menú que contiene los botones principales
     */
    public Menu getPanelMenu() {
        return menu;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setOpaque(true);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane bg;
    // End of variables declaration//GEN-END:variables
}
